### ISSUE TITLE
环境错误

### ISSUE THREAD

**Issue by wjy3326** [boy56/PLMEE#4]
根据你的环境，安装torch==1.4跟allennlp==0.9.0，出现错误：

Traceback (most recent call last):
  File "extractor_trainer.py", line 6, in <module>
    from allennlp.modules.token_embedders.bert_token_embedder import PretrainedBertEmbedder
  File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/allennlp/modules/__init__.py", line 9, in <module>
    from allennlp.modules.elmo import Elmo
  File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 20, in <module>
    from allennlp.modules.highway import Highway
  File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/allennlp/modules/highway.py", line 12, in <module>
    class Highway(torch.nn.Module):
  File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/allennlp/modules/highway.py", line 49, in Highway
    def forward(self, inputs: torch.Tensor) -> torch.Tensor:  # pylint: disable=arguments-differ
  File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/overrides/signature.py", line 104, in ensure_signature_is_compatible
    method_name,
  File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/overrides/signature.py", line 211, in ensure_all_positional_args_defined_in_sub
    raise TypeError(f"{method_name}: `{super_param.name}` must be present")
TypeError: Highway.forward: `input` must be present

**Comment by boy56** [comment]
> 根据你的环境，安装torch==1.4跟allennlp==0.9.0，出现错误：
> 
> Traceback (most recent call last): File "extractor_trainer.py", line 6, in from allennlp.modules.token_embedders.bert_token_embedder import PretrainedBertEmbedder File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/allennlp/modules/**init**.py", line 9, in from allennlp.modules.elmo import Elmo File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 20, in from allennlp.modules.highway import Highway File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/allennlp/modules/highway.py", line 12, in class Highway(torch.nn.Module): File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/allennlp/modules/highway.py", line 49, in Highway def forward(self, inputs: torch.Tensor) -> torch.Tensor: # pylint: disable=arguments-differ File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/overrides/overrides.py", line 88, in overrides return _overrides(method, check_signature, check_at_runtime) File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/overrides/overrides.py", line 114, in _overrides _validate_method(method, super_class, check_signature) File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/overrides/overrides.py", line 135, in _validate_method ensure_signature_is_compatible(super_method, method, is_static) File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/overrides/signature.py", line 104, in ensure_signature_is_compatible method_name, File "/home/user/anaconda3/envs/plmee/lib/python3.6/site-packages/overrides/signature.py", line 211, in ensure_all_positional_args_defined_in_sub raise TypeError(f"{method_name}: `{super_param.name}` must be present") TypeError: Highway.forward: `input` must be present

建议查一下环境安装时候的报错信息，这些我没遇到过。这版模型比较关键的就是allennlp和torch的版本。根据这个报错信息我查了下，不知道网址 https://stackoverflow.com/questions/67348569/why-i-getting-highway-forward-input-must-be-present-when-running-from-elmof  的方法是否管用。

**Comment by wjy3326** [comment]
好的，根据你的方法，已经解决了，谢谢！
